# Generated by Django 6.1 on 2026-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('static', 'Static'), ('digital', 'Digital'), ('light_pole', 'Light Pole'), ('airport', 'Airport'), ('station', 'Station')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('under_maintanance', 'Under Maintanance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('region', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('width_meters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_meters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('illuminated', models.BooleanField(default=False)),
                ('backlit', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='billboards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_code'],
            },
        ),
    ]
