# Generated by Django 6.1 on 2026-09-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
