# Generated by Django 6.1 on 2026-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0002_rename_update_at_billboard_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='side',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='billboard',
            name='structure_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
